{"matches":[{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"74.1.2"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"b00bc49338ac030d","name":"setuptools","version":"74.1.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-74.1.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-74.1.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-74.1.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-74.1.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-74.1.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-74.1.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:74.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@74.1.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-q2x7-8rv6-6q7h","dataSource":"https://github.com/advisories/GHSA-q2x7-8rv6-6q7h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through indirect reference to format method","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.06592},"relatedVulnerabilities":[{"id":"CVE-2024-56326","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56326","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/48b0687e05a5466a91cd5812d604fa37ad0943b4","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-q2x7-8rv6-6q7h"],"description":"Jinja is an extensible templating engine. Prior to 3.1.5, An oversight in how the Jinja sandboxed environment detects calls to str.format allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to store a reference to a malicious string's format method, then pass that to a filter that calls it. No such filters are built-in to Jinja, but could be present through custom filters in an application. After the fix, such indirect calls are also handled by the sandbox. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.4"}},"found":{"versionConstraint":"<=3.1.4 (python)","vulnerabilityID":"GHSA-q2x7-8rv6-6q7h"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"58cad37a398c1650","name":"jinja2","version":"3.1.4","type":"python","locations":[{"path":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-gmj6-6f8f-6699","dataSource":"https://github.com/advisories/GHSA-gmj6-6f8f-6699","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through malicious filenames","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.044160000000000005},"relatedVulnerabilities":[{"id":"CVE-2024-56201","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56201","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/767b23617628419ae3709ccfb02f9602ae9fe51f","https://github.com/pallets/jinja/issues/1792","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-gmj6-6f8f-6699"],"description":"Jinja is an extensible templating engine. In versions on the 3.x branch prior to 3.1.5, a bug in the Jinja compiler allows an attacker that controls both the content and filename of a template to execute arbitrary Python code, regardless of if Jinja's sandbox is used. To exploit the vulnerability, an attacker needs to control both the filename and the contents of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates where the template author can also choose the template filename. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.4"}},"found":{"versionConstraint":">=3.0.0,<=3.1.4 (python)","vulnerabilityID":"GHSA-gmj6-6f8f-6699"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"58cad37a398c1650","name":"jinja2","version":"3.1.4","type":"python","locations":[{"path":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-vqfr-h8mv-ghfj","dataSource":"https://github.com/advisories/GHSA-vqfr-h8mv-ghfj","namespace":"github:language:python","severity":"Critical","urls":[],"description":"h11 accepts some malformed Chunked-Encoding bodies","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-43859","epss":0.00044,"percentile":0.13131,"date":"2025-06-02"}],"fix":{"versions":["0.16.0"],"state":"fixed"},"advisories":[],"risk":0.03982},"relatedVulnerabilities":[{"id":"CVE-2025-43859","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-43859","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/python-hyper/h11/commit/114803a29ce50116dc47951c690ad4892b1a36ed","https://github.com/python-hyper/h11/security/advisories/GHSA-vqfr-h8mv-ghfj"],"description":"h11 is a Python implementation of HTTP/1.1. Prior to version 0.16.0, a leniency in h11's parsing of line terminators in chunked-coding message bodies can lead to request smuggling vulnerabilities under certain conditions. This issue has been patched in version 0.16.0. Since exploitation requires the combination of buggy h11 with a buggy (reverse) proxy, fixing either component is sufficient to mitigate this issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-43859","epss":0.00044,"percentile":0.13131,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"h11","version":"0.14.0"}},"found":{"versionConstraint":"<0.16.0 (python)","vulnerabilityID":"GHSA-vqfr-h8mv-ghfj"},"fix":{"suggestedVersion":"0.16.0"}}],"artifact":{"id":"f36ffff68ecb9934","name":"h11","version":"0.14.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/h11-0.14.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/h11-0.14.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/h11-0.14.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/h11-0.14.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/h11-0.14.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/h11-0.14.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:nathaniel_j__smith_project:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith_project:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smithproject:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smithproject:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith_project:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smithproject:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njs_project:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njs_project:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njsproject:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njsproject:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python-h11:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python-h11:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python_h11:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python_h11:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njs_project:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:h11:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:h11:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njs:python-h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njs:python_h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njsproject:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python-h11:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python_h11:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:python:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:h11:h11:0.14.0:*:*:*:*:*:*:*","cpe:2.3:a:njs:h11:0.14.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/h11@0.14.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-79v4-65xg-pq4g","dataSource":"https://github.com/advisories/GHSA-79v4-65xg-pq4g","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"epss":[{"cve":"CVE-2024-12797","epss":0.0013,"percentile":0.33813,"date":"2025-06-02"}],"fix":{"versions":["44.0.1"],"state":"fixed"},"advisories":[],"risk":0.039},"relatedVulnerabilities":[{"id":"CVE-2024-12797","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-12797","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/738d4f9fdeaad57660dcba50a619fafced3fd5e9","https://github.com/openssl/openssl/commit/798779d43494549b611233f92652f0da5328fbe7","https://github.com/openssl/openssl/commit/87ebd203feffcf92ad5889df92f90bb0ee10a699","https://openssl-library.org/news/secadv/20250211.txt","http://www.openwall.com/lists/oss-security/2025/02/11/3","http://www.openwall.com/lists/oss-security/2025/02/11/4","https://security.netapp.com/advisory/ntap-20250214-0001/"],"description":"Issue summary: Clients using RFC7250 Raw Public Keys (RPKs) to authenticate a\nserver may fail to notice that the server was not authenticated, because\nhandshakes don't abort as expected when the SSL_VERIFY_PEER verification mode\nis set.\n\nImpact summary: TLS and DTLS connections using raw public keys may be\nvulnerable to man-in-middle attacks when server authentication failure is not\ndetected by clients.\n\nRPKs are disabled by default in both TLS clients and TLS servers.  The issue\nonly arises when TLS clients explicitly enable RPK use by the server, and the\nserver, likewise, enables sending of an RPK instead of an X.509 certificate\nchain.  The affected clients are those that then rely on the handshake to\nfail when the server's RPK fails to match one of the expected public keys,\nby setting the verification mode to SSL_VERIFY_PEER.\n\nClients that enable server-side raw public keys can still find out that raw\npublic key verification failed by calling SSL_get_verify_result(), and those\nthat do, and take appropriate action, are not affected.  This issue was\nintroduced in the initial implementation of RPK support in OpenSSL 3.2.\n\nThe FIPS modules in 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":6.3,"exploitabilityScore":2.9,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-12797","epss":0.0013,"percentile":0.33813,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"43.0.1"}},"found":{"versionConstraint":">=42.0.0,<44.0.1 (python)","vulnerabilityID":"GHSA-79v4-65xg-pq4g"},"fix":{"suggestedVersion":"44.0.1"}}],"artifact":{"id":"7b86e7951279baae","name":"cryptography","version":"43.0.1","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-43.0.1.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-43.0.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-43.0.1.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-43.0.1.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:43.0.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:43.0.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@43.0.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-cpwx-vrp4-4pq7","dataSource":"https://github.com/advisories/GHSA-cpwx-vrp4-4pq7","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja2 vulnerable to sandbox breakout through attr filter selecting format method","cvss":[],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}],"fix":{"versions":["3.1.6"],"state":"fixed"},"advisories":[],"risk":0.017},"relatedVulnerabilities":[{"id":"CVE-2025-27516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-27516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/90457bbf33b8662926ae65cdde4c4c32e756e403","https://github.com/pallets/jinja/security/advisories/GHSA-cpwx-vrp4-4pq7","https://lists.debian.org/debian-lts-announce/2025/04/msg00045.html"],"description":"Jinja is an extensible templating engine. Prior to 3.1.6, an oversight in how the Jinja sandboxed environment interacts with the |attr filter allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to use the |attr filter to get a reference to a string's plain format method, bypassing the sandbox. After the fix, the |attr filter no longer bypasses the environment's attribute lookup. This vulnerability is fixed in 3.1.6.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.4"}},"found":{"versionConstraint":"<=3.1.5 (python)","vulnerabilityID":"GHSA-cpwx-vrp4-4pq7"},"fix":{"suggestedVersion":"3.1.6"}}],"artifact":{"id":"58cad37a398c1650","name":"jinja2","version":"3.1.4","type":"python","locations":[{"path":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/jinja2-3.1.4.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.4:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.4","upstreams":[]}}],"source":{"type":"sbom-file","target":"data-science-stack-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/data-science-stack-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/data-science-stack-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-04T10:11:33.133633+01:00"}}
