{"matches":[{"vulnerability":{"id":"GHSA-cf7p-gm2m-833m","dataSource":"https://github.com/advisories/GHSA-cf7p-gm2m-833m","namespace":"github:language:python","severity":"High","urls":[],"description":"cryptography mishandles SSH certificates","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-38325","epss":0.00791,"percentile":0.72866,"date":"2025-06-02"}],"fix":{"versions":["41.0.2"],"state":"fixed"},"advisories":[],"risk":0.59325},"relatedVulnerabilities":[{"id":"CVE-2023-38325","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-38325","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/compare/41.0.1...41.0.2","https://github.com/pyca/cryptography/issues/9207","https://github.com/pyca/cryptography/pull/9208","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NMCCTYY3CSNQBFFYYC5DAV6KATHWCUZK/","https://pypi.org/project/cryptography/#history","https://security.netapp.com/advisory/ntap-20230824-0010/","https://github.com/pyca/cryptography/compare/41.0.1...41.0.2","https://github.com/pyca/cryptography/issues/9207","https://github.com/pyca/cryptography/pull/9208","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NMCCTYY3CSNQBFFYYC5DAV6KATHWCUZK/","https://pypi.org/project/cryptography/#history","https://security.netapp.com/advisory/ntap-20230824-0010/"],"description":"The cryptography package before 41.0.2 for Python mishandles SSH certificates that have critical options.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-38325","epss":0.00791,"percentile":0.72866,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":">=40.0.0,<41.0.2 (python)","vulnerabilityID":"GHSA-cf7p-gm2m-833m"},"fix":{"suggestedVersion":"41.0.2"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.65933,"date":"2025-06-02"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.65933,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"67.8.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"5f3305a6f9096a13","name":"setuptools","version":"67.8.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:67.8.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@67.8.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfhm-5ghh-2f97","dataSource":"https://github.com/advisories/GHSA-jfhm-5ghh-2f97","namespace":"github:language:python","severity":"Medium","urls":[],"description":"cryptography vulnerable to NULL-dereference when loading PKCS7 certificates","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63036,"date":"2025-06-02"}],"fix":{"versions":["41.0.6"],"state":"fixed"},"advisories":[],"risk":0.24906500000000004},"relatedVulnerabilities":[{"id":"CVE-2023-49083","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-49083","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/","https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63036,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":">=3.1,<41.0.6 (python)","vulnerabilityID":"GHSA-jfhm-5ghh-2f97"},"fix":{"suggestedVersion":"41.0.6"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-6vqw-3v5j-54x4","dataSource":"https://github.com/advisories/GHSA-6vqw-3v5j-54x4","namespace":"github:language:python","severity":"High","urls":[],"description":"cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49168,"date":"2025-06-02"}],"fix":{"versions":["42.0.4"],"state":"fixed"},"advisories":[],"risk":0.19275},"relatedVulnerabilities":[{"id":"CVE-2024-26130","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-26130","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4","https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55","https://github.com/pyca/cryptography/pull/10423","https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-26130","epss":0.00257,"percentile":0.49168,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":">=38.0.0,<42.0.4 (python)","vulnerabilityID":"GHSA-6vqw-3v5j-54x4"},"fix":{"suggestedVersion":"42.0.4"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"67.8.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"5f3305a6f9096a13","name":"setuptools","version":"67.8.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-67.8.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:67.8.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@67.8.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29442,"date":"2025-06-02"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29442,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"23.1.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"b49776d227443466","name":"pip","version":"23.1.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/pip-23.1.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/pip-23.1.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/pip-23.1.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/pip-23.1.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/pip-23.1.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/pip-23.1.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:23.1.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:23.1.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@23.1.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-h4gh-qq45-vh27","dataSource":"https://github.com/advisories/GHSA-h4gh-qq45-vh27","namespace":"github:language:python","severity":"Medium","urls":[],"description":"pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["43.0.1"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":">=37.0.0,<43.0.1 (python)","vulnerabilityID":"GHSA-h4gh-qq45-vh27"},"fix":{"suggestedVersion":"43.0.1"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-jm77-qphf-c4w8","dataSource":"https://github.com/advisories/GHSA-jm77-qphf-c4w8","namespace":"github:language:python","severity":"Low","urls":[],"description":"pyca/cryptography's wheels include vulnerable OpenSSL","cvss":[],"fix":{"versions":["41.0.3"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":">=0.8,<41.0.3 (python)","vulnerabilityID":"GHSA-jm77-qphf-c4w8"},"fix":{"suggestedVersion":"41.0.3"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-v8gr-m533-ghj9","dataSource":"https://github.com/advisories/GHSA-v8gr-m533-ghj9","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.4"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"41.0.0"}},"found":{"versionConstraint":">=2.5,<41.0.4 (python)","vulnerabilityID":"GHSA-v8gr-m533-ghj9"},"fix":{"suggestedVersion":"41.0.4"}}],"artifact":{"id":"695de9be94a7d7ce","name":"cryptography","version":"41.0.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/cryptography-41.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:41.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@41.0.0","upstreams":[]}}],"source":{"type":"sbom-file","target":"quickcerts-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/quickcerts-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/quickcerts-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T13:11:19.470506+01:00"}}
